// import React, { useState, useEffect } from "react";
// import { motion } from "framer-motion";

// const summaryText =
//   "This video demonstrates building a responsive live streaming UI with comments, live transcript, timestamps, and interactive features using React, TailwindCSS, daisyUI, and Framer Motion.";

// const Summary = () => {
//   const [displayedText, setDisplayedText] = useState("");
//   const [index, setIndex] = useState(0);

//   useEffect(() => {
//     const interval = setInterval(() => {
//       setDisplayedText(summaryText.slice(0, index + 1));
//       setIndex((prev) => (prev + 1 > summaryText.length ? 0 : prev + 1));
//     }, 50); // typing speed (ms)

//     return () => clearInterval(interval);
//   }, [index]);

//   return (
//     <motion.div
//       initial={{ opacity: 0 }}
//       animate={{ opacity: 1 }}
//       transition={{ duration: 0.5 }}
//       className="bg-gray-700 text-white p-4 rounded-lg shadow-md w-[500px] font-normal"
//     >
//       <span className="text-gray-300">{displayedText}</span>
//       <span className="animate-pulse">|</span>
//     </motion.div>
//   );
// };

// export default Summary;

import React, { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { FaRobot } from "react-icons/fa";

const summaryText =
  "This stream covers building a responsive live streaming UI with comments, live transcript, timestamps, and interactive features using React, TailwindCSS, and Framer Motion. Key topics include real-time chat, HLS video playback, and modular component design.";

const Summary = () => {
  const [displayedText, setDisplayedText] = useState("");
  const [index, setIndex] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setDisplayedText(summaryText.slice(0, index + 1));
      setIndex((prev) => (prev + 1 > summaryText.length ? 0 : prev + 1));
    }, 40);
    return () => clearInterval(interval);
  }, [index]);

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="flex flex-col gap-3 h-full"
    >
      <div className="flex items-center gap-2">
        <span className="w-2 h-2 rounded-full bg-[#7b35d9] animate-pulse shadow-[0_0_6px_#7b35d9]" />
        <span className="text-[10px] font-bold uppercase tracking-widest text-gray-500">
          AI Summary
        </span>
        <FaRobot size={10} className="text-[#7b35d9] ml-auto" />
      </div>

      <div className="bg-gray-900 border border-[#7b35d9]/20 rounded-xl p-4 text-sm text-gray-300 leading-relaxed min-h-[120px]">
        {displayedText}
        <span className="inline-block w-0.5 h-4 bg-[#7b35d9] ml-0.5 animate-pulse align-middle" />
      </div>

      <p className="text-[10px] text-gray-600 flex items-center gap-1">
        <FaRobot size={9} className="text-[#7b35d9]" />
        Generated by StreamAI — updates every 60s
      </p>
    </motion.div>
  );
};

export default Summary;
